/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunityIdRouteImport } from './routes/opportunity.$id'
import { Route as DemoIdRouteImport } from './routes/demo.$id'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIdRoute = OpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/demo/$id': typeof DemoIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/demo/$id': typeof DemoIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/demo/$id': typeof DemoIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/demo/$id' | '/opportunity/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/demo/$id' | '/opportunity/$id'
  id: '__root__' | '/' | '/explore' | '/demo/$id' | '/opportunity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  DemoIdRoute: typeof DemoIdRoute
  OpportunityIdRoute: typeof OpportunityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$id': {
      id: '/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof OpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id': {
      id: '/demo/$id'
      path: '/demo/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  DemoIdRoute: DemoIdRoute,
  OpportunityIdRoute: OpportunityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
