/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as MyBusinessesRouteImport } from './routes/my-businesses'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunityIdRouteImport } from './routes/opportunity.$id'
import { Route as DemoIdRouteImport } from './routes/demo.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiExploreIndexRouteImport } from './routes/api/explore/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as ApiBuildIndexRouteImport } from './routes/api/build/index'
import { Route as ApiAgentIndexRouteImport } from './routes/api/agent/index'
import { Route as ApiGuestPrototypesRouteImport } from './routes/api/guest/prototypes'
import { Route as ApiGuestIdeasRouteImport } from './routes/api/guest/ideas'
import { Route as ApiExploreSearchRouteImport } from './routes/api/explore/search'
import { Route as ApiBuildStatusRouteImport } from './routes/api/build/status'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBusinessesRoute = MyBusinessesRouteImport.update({
  id: '/my-businesses',
  path: '/my-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityIdRoute = OpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiExploreIndexRoute = ApiExploreIndexRouteImport.update({
  id: '/api/explore/',
  path: '/api/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildIndexRoute = ApiBuildIndexRouteImport.update({
  id: '/api/build/',
  path: '/api/build/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentIndexRoute = ApiAgentIndexRouteImport.update({
  id: '/api/agent/',
  path: '/api/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestPrototypesRoute = ApiGuestPrototypesRouteImport.update({
  id: '/api/guest/prototypes',
  path: '/api/guest/prototypes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestIdeasRoute = ApiGuestIdeasRouteImport.update({
  id: '/api/guest/ideas',
  path: '/api/guest/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExploreSearchRoute = ApiExploreSearchRouteImport.update({
  id: '/api/explore/search',
  path: '/api/explore/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildStatusRoute = ApiBuildStatusRouteImport.update({
  id: '/api/build/status',
  path: '/api/build/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/explore': typeof ExploreRoute
  '/my-businesses': typeof MyBusinessesRoute
  '/studio': typeof StudioRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/$id': typeof DemoIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/api/build/status': typeof ApiBuildStatusRoute
  '/api/explore/search': typeof ApiExploreSearchRoute
  '/api/guest/ideas': typeof ApiGuestIdeasRoute
  '/api/guest/prototypes': typeof ApiGuestPrototypesRoute
  '/api/agent/': typeof ApiAgentIndexRoute
  '/api/build/': typeof ApiBuildIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/explore/': typeof ApiExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/explore': typeof ExploreRoute
  '/my-businesses': typeof MyBusinessesRoute
  '/studio': typeof StudioRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/$id': typeof DemoIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/api/build/status': typeof ApiBuildStatusRoute
  '/api/explore/search': typeof ApiExploreSearchRoute
  '/api/guest/ideas': typeof ApiGuestIdeasRoute
  '/api/guest/prototypes': typeof ApiGuestPrototypesRoute
  '/api/agent': typeof ApiAgentIndexRoute
  '/api/build': typeof ApiBuildIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/explore': typeof ApiExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/explore': typeof ExploreRoute
  '/my-businesses': typeof MyBusinessesRoute
  '/studio': typeof StudioRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/$id': typeof DemoIdRoute
  '/opportunity/$id': typeof OpportunityIdRoute
  '/api/build/status': typeof ApiBuildStatusRoute
  '/api/explore/search': typeof ApiExploreSearchRoute
  '/api/guest/ideas': typeof ApiGuestIdeasRoute
  '/api/guest/prototypes': typeof ApiGuestPrototypesRoute
  '/api/agent/': typeof ApiAgentIndexRoute
  '/api/build/': typeof ApiBuildIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/explore/': typeof ApiExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/my-businesses'
    | '/studio'
    | '/auth/callback'
    | '/demo/$id'
    | '/opportunity/$id'
    | '/api/build/status'
    | '/api/explore/search'
    | '/api/guest/ideas'
    | '/api/guest/prototypes'
    | '/api/agent/'
    | '/api/build/'
    | '/api/chat/'
    | '/api/explore/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/my-businesses'
    | '/studio'
    | '/auth/callback'
    | '/demo/$id'
    | '/opportunity/$id'
    | '/api/build/status'
    | '/api/explore/search'
    | '/api/guest/ideas'
    | '/api/guest/prototypes'
    | '/api/agent'
    | '/api/build'
    | '/api/chat'
    | '/api/explore'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/my-businesses'
    | '/studio'
    | '/auth/callback'
    | '/demo/$id'
    | '/opportunity/$id'
    | '/api/build/status'
    | '/api/explore/search'
    | '/api/guest/ideas'
    | '/api/guest/prototypes'
    | '/api/agent/'
    | '/api/build/'
    | '/api/chat/'
    | '/api/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  MyBusinessesRoute: typeof MyBusinessesRoute
  StudioRoute: typeof StudioRoute
  DemoIdRoute: typeof DemoIdRoute
  OpportunityIdRoute: typeof OpportunityIdRoute
  ApiBuildStatusRoute: typeof ApiBuildStatusRoute
  ApiExploreSearchRoute: typeof ApiExploreSearchRoute
  ApiGuestIdeasRoute: typeof ApiGuestIdeasRoute
  ApiGuestPrototypesRoute: typeof ApiGuestPrototypesRoute
  ApiAgentIndexRoute: typeof ApiAgentIndexRoute
  ApiBuildIndexRoute: typeof ApiBuildIndexRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiExploreIndexRoute: typeof ApiExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-businesses': {
      id: '/my-businesses'
      path: '/my-businesses'
      fullPath: '/my-businesses'
      preLoaderRoute: typeof MyBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$id': {
      id: '/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof OpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id': {
      id: '/demo/$id'
      path: '/demo/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/explore/': {
      id: '/api/explore/'
      path: '/api/explore'
      fullPath: '/api/explore/'
      preLoaderRoute: typeof ApiExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/': {
      id: '/api/build/'
      path: '/api/build'
      fullPath: '/api/build/'
      preLoaderRoute: typeof ApiBuildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/': {
      id: '/api/agent/'
      path: '/api/agent'
      fullPath: '/api/agent/'
      preLoaderRoute: typeof ApiAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest/prototypes': {
      id: '/api/guest/prototypes'
      path: '/api/guest/prototypes'
      fullPath: '/api/guest/prototypes'
      preLoaderRoute: typeof ApiGuestPrototypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest/ideas': {
      id: '/api/guest/ideas'
      path: '/api/guest/ideas'
      fullPath: '/api/guest/ideas'
      preLoaderRoute: typeof ApiGuestIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explore/search': {
      id: '/api/explore/search'
      path: '/api/explore/search'
      fullPath: '/api/explore/search'
      preLoaderRoute: typeof ApiExploreSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/status': {
      id: '/api/build/status'
      path: '/api/build/status'
      fullPath: '/api/build/status'
      preLoaderRoute: typeof ApiBuildStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ExploreRoute: ExploreRoute,
  MyBusinessesRoute: MyBusinessesRoute,
  StudioRoute: StudioRoute,
  DemoIdRoute: DemoIdRoute,
  OpportunityIdRoute: OpportunityIdRoute,
  ApiBuildStatusRoute: ApiBuildStatusRoute,
  ApiExploreSearchRoute: ApiExploreSearchRoute,
  ApiGuestIdeasRoute: ApiGuestIdeasRoute,
  ApiGuestPrototypesRoute: ApiGuestPrototypesRoute,
  ApiAgentIndexRoute: ApiAgentIndexRoute,
  ApiBuildIndexRoute: ApiBuildIndexRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiExploreIndexRoute: ApiExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
